import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
vgsales = pd.read_csv("vgsales.csv")
data = vgsales.dropna(subset = ["NA_Sales", "EU_Sales", "Global_Sales", "JP_Sales"])
print(data.isnull().sum())
plt.figure(figsize=(10,5))
sns.histplot(data=data,x="Global_Sales", bins=40 , kde=True)
plt.xlabel("Global Sales")  
plt.ylabel("Count")
plt.title("Global Sales distribution")
plt.show()
plt.figure(figsize=(10,5))
sns.scatterplot(data=data,x="NA_Sales", y="EU_Sales", alpha=0.5)
plt.title("NA to EU sales comparison")
plt.xlabel("NA_Sales")
plt.ylabel("EU_Sales")
plt.show()
plt.figure(figsize=(10,5))
sns.scatterplot(data=data,x="NA_Sales", y="JP_Sales", alpha=0.5)
plt.title("NA to JP sales comparison")
plt.xlabel("NA_Sales")
plt.ylabel("JP_Sales")
plt.show()